### ISSUE TITLE
invalid algorithm in CrunchThePrimes exercise

### ISSUE THREAD

**Issue by GitCMDR** [inancgumus/learngo#103]
Part of the exercise (https://github.com/inancgumus/learngo/tree/master/13-loops/exercises/10-crunch-the-primes) asks the reader to re-implement this algorithm (https://stackoverflow.com/questions/1801391/how-to-create-the-most-compact-mapping-n-%e2%86%92-isprimen-up-to-a-limit-n/1801446#1801446) in order to build the logic to pass the challenge. 

The expected output is: 
//  go run main.go 2 4 6 7 a 9 c 11 x 12 13
//    2 7 11 13
//
//  go run main.go 1 2 3 5 7 A B C
//    2 3 5 7

Somehow, I kept getting 1 as part of the output of my implementation.

//  go run main.go 2 4 6 7 a 9 c 11 x 12 13
//    2 7 11 13 
//
//  go run main.go 1 2 3 5 7 A B C
//    1 2 3 5 7 

![image](https://user-images.githubusercontent.com/25272428/139582445-02c5f087-956b-48a6-b2d7-78db0d4ad7c3.png)

After further testing, it appears that the algorithm we are being asked to use is incorrect as it will return 1, even though 1 is not a prime number (https://www.wgtn.ac.nz/science/ask-a-researcher/is-1-a-prime-number)

**Comment by ErdemOzgen** [comment]
Nice catch but theorem based on condition where n greater than 2 and also other conditions. You can look  [link](https://www.geeksforgeeks.org/aks-primality-test/#:~:text=The%20AKS%20primality,f%20and%20g%20.%C2%A0) for more details.

**Comment by ErdemOzgen** [comment]
On the solution of this problem @inancgumus use 
[Solutions Source Code](https://github.com/inancgumus/learngo/blob/master/13-loops/exercises/10-crunch-the-primes/solution/main.go)
```go
		// not a prime
		case n <= 1 || n%2 == 0 || n%3 == 0:
			continue
		}
```
in case of n equal to 1. AKS primality test is based on n must be greater than 2 and other conditions that can be found more detailly in [here](https://www.geeksforgeeks.org/aks-primality-test/#:~:text=The%20AKS%20primality,f%20and%20g). For your python code, you can add an extra condition for n equal to 1.
