### ISSUE TITLE
Invalid indirect issue in Pointers' exercise #3-fix-the crash

### ISSUE THREAD

**Issue by AkiAno** [inancgumus/learngo#104]
```
package main

import "fmt"

type computer struct {
	brand string
}

func main() {
	c := &computer{} 
	change(c, "apple")
	fmt.Printf("brand: %s\n", *c.brand) // need to remove *
}

func change(c *computer, brand string) {
	c.brand = brand
}
```
While printing pointed values, we get "invalid indirect of c.brand (type string)" issue. 
The fix will be to call c.brand without *.

**Comment by nirsht** [comment]
hey, anyone on it ? 
I can fix it

**Comment by inancgumus** [comment]
Hey, @AkiAno, you can use [Discussions](https://github.com/inancgumus/learngo/discussions/categories/q-a-about-exercises-and-solutions) here for your questions about exercises and their solutions.
