### ISSUE TITLE
Richter Scale 2 typo

### ISSUE THREAD

**Issue by ZerkerEOD** [inancgumus/learngo#117]
This is just my OCD. For the project learngo\12-switch\exercises\02-richter-scale-2\main.go in the comments for the expected output has the user expecting to put in plural and then return plural a different way.

```
//  go run main.go aliens
//   alien's richter scale is unknown

```
The expected input is "aliens" but then the s gets turned into 's which is getting added to all outputs. So, really it looks like the s vanishes.

**Comment by ZerkerEOD** [comment]
I do want to say great course though, I am loving it.

**Comment by inancgumus** [comment]
Ah, thanks!
