### ISSUE TITLE
website link in example code not working

### ISSUE THREAD

**Issue by jahway603** [inancgumus/learngo#123]
The website link located here, https://github.com/inancgumus/learngo/blob/master/11-if/exercises/04-vowel-or-cons/main.go#L18, does not work. Not sure of a better link, or I would have changed and submitted a PR for the change.

**Comment by inancgumus** [comment]
Thanks for reporting the issue. Would you like to send a fix, maybe changing the link to [this](https://en.wikipedia.org/wiki/Semivowel)?

**Comment by jahway603** [comment]
That link was confusing to read, so I found one for each Y & W that are much easier to read & understand.

**Comment by inancgumus** [comment]
Makes sense, thanks.
