### ISSUE TITLE
Why use int64 instead of uint32?

### ISSUE THREAD

**Issue by Sijoma** [inancgumus/learngo#35]
Hey Inanc,

why do you use int64 for the speed of light variable? uint32 should be enough, right?. 

https://github.com/inancgumus/learngo/blob/65e854c4ae4b56192054b7c93ed61295c79c01a6/09-go-type-system/exercises/01-optimal-types/solution/main.go#L32##

Is it also correct that the code from the non English letter prints this to the console: 
"a non-english letter: 199"

Shouldn't 199 be the non-english letter instead of the number?
I used fmt.Printf("a non-english letter:%c", unicode) to correct this.

Thanks for your content btw!

**Comment by inancgumus** [comment]
Hey Sijoma,

Good catches, thanks. Is it possible for you to send a PR? So I can merge it.

Thanks.
