### ISSUE TITLE
Multiple Questions

### ISSUE THREAD

**Issue by firasuke** [inancgumus/learngo#68]
Upon solving the exercises (in order) I compiled the following list of questions:

- What's wrong with the numbering of the subdirectories inside [06-variables/04-assignments](https://github.com/inancgumus/learngo/tree/master/06-variables/04-assignment)?

- Can you please further elaborate on what the exercise/question is/was for this [solution](https://github.com/inancgumus/learngo/blob/master/06-variables/06-project-greeter/exercises/solution-to-the-lecture-exercise/main.go)?

- Why is [03-refactor-feet-to-meters](https://github.com/inancgumus/learngo/tree/master/10-constants/03-refactor-feet-to-meters) not in the exercises section of `10-constants`?

- Why isn't [11-if/02-if-statement/05-challenge-userpass](https://github.com/inancgumus/learngo/tree/master/11-if/02-if-statement/05-challenge-userpass) in the exercises section?

- Why isn't [14-arrays/06-challenge-moodly](https://github.com/inancgumus/learngo/tree/master/14-arrays/06-challenge-moodly) and [14-arrays/10-challenge-moodly-2](https://github.com/inancgumus/learngo/tree/master/14-arrays/10-challenge-moodly-2) not in the exercises ection of `14-arrays`?

- What's wrong with the commented numbers in [16-slices/12-full-slice-expressions/2-example](https://github.com/inancgumus/learngo/blob/master/16-slices/12-full-slice-expressions/2-example/main.go) (`#4` is before `#3` and so on) and in [16-slices/13-make/2-example/](https://github.com/inancgumus/learngo/blob/master/16-slices/13-make/2-example/main.go) (`#6` repeated twice and `#7` is before the second `#6`) and in [16-slices/14-copy/02-hacker-incident/](https://github.com/inancgumus/learngo/blob/master/16-slices/14-copy/02-hacker-incident/main.go) (No `#8` and `#1` after `#9`)?

- Why aren't the solutions for chapters [20](https://github.com/inancgumus/learngo/tree/master/20-project-spam-masker) and [21](https://github.com/inancgumus/learngo/tree/master/21-project-text-wrapper) in their own respective `solution` directory?

**Comment by inancgumus** [comment]
Could you collect all your questions under this issue only?

**Comment by firasuke** [comment]
Ok, will do.

**Comment by inancgumus** [comment]
> What's wrong with the numbering of the subdirectories inside 06-variables/04-assignments?
I think we can fix these.

> Can you please further elaborate on what the exercise/question is/was for this solution?
> Why is 03-refactor-feet-to-meters not in the exercises section of 10-constants?
> Why isn't 11-if/02-if-statement/05-challenge-userpass in the exercises section?
> Why isn't 14-arrays/06-challenge-moodly and 14-arrays/10-challenge-moodly-2 not in the exercises ection of 14-arrays?
> Why aren't the solutions for chapters 20 and 21 in their own respective solution directory?
The video lectures talk about these exercises. I think we should add them here as text.

> What's wrong with the commented numbers...
I explain those steps in the slice lectures in that order.

Thank you for your review! Appreciated.

**Comment by firasuke** [comment]
> Thank you for your review! Appreciated.

Glad I could help!

**Comment by firasuke** [comment]
Should I proceed to close this issue?

**Comment by inancgumus** [comment]
Sure, please go ahead.

**Comment by firasuke** [comment]
Alright.
