### ISSUE TITLE
21-project-text-wrapper exceeds maxWidth line length

### ISSUE THREAD

**Issue by NoThisIsPatrik** [inancgumus/learngo#74]
21-project-text-wrapper prints lines longer than 40 runes.

Since you're printing 40 runes, then continuing until a word break, the lines end up being longer than maxWidth by however much of a word is left.

[example_output.txt](https://github.com/inancgumus/learngo/files/6166670/example_output.txt)

This doesn't seem to match the original request, nor what word processors do.

**Comment by inancgumus** [comment]
Could you fix it and send a PR?

**Comment by inancgumus** [comment]
I'm reviewing your code, btw could you use: `gofmt -w main.go`?
