### ISSUE TITLE
switch - exercise 02 richter scale - solution wrong

### ISSUE THREAD

**Issue by longwuyuan** [inancgumus/learngo#80]
running main.go with a string of 2 words produces wrong output. For example one of the test cases in the exercise is `go run main.go "very minor"`   . This test produces wrong output as the program is looking for os.Args[1]

**Comment by longwuyuan** [comment]
same problem in other exercises where the test case is 2 words passed to main.go instead of 1 word. I am not interested in a fix too much as I am interested in a ack that this is a correct assessment of the issue. of course can concatenate os.Args[1] and os.Args[2] .......

**Comment by longwuyuan** [comment]
@inancgumus please comment

**Comment by inancgumus** [comment]
@longwuyuan It works as expected?

See: https://play.golang.org/p/g-3VGXehhuM
