### ISSUE TITLE
path searcher exercise solution always prints lower-cased paths (13-loops / exercise / 09 / 02)

### ISSUE THREAD

**Issue by theclive** [inancgumus/learngo#84]
This is a small issue, but one you may want to consider 😉 

With reference to [learngo/13-loops/exercises/09-word-finder-exercises/02-path-searcher/solution/main.go](https://github.com/inancgumus/learngo/blob/ede39bfe59abb629f675624a8f59d83ca49b7b09/13-loops/exercises/09-word-finder-exercises/02-path-searcher/solution/main.go)

If a directory/folder legitimately contains a capital letter, converting `w` to lowercase results in the output displaying the path incorrectly lower-cased.  One should only `ToLower` for the comparison, not the output to the user.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/23497305/120923195-8c566680-c6cd-11eb-823a-d741ae020da6.png">

Sample correct vs incorrect output:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/23497305/120923236-c7f13080-c6cd-11eb-9172-13cf6d29da57.png">

**Comment by inancgumus** [comment]
Thanks, this seems right. Could you send a PR?
