### ISSUE TITLE
Chapter 11-if, solution of 04-vowel-or-cons  exercise, use strings.ContainsAny instead of strings.IndexAny

### ISSUE THREAD

**Issue by rkh-hash** [inancgumus/learngo#85]
Hi @inancgumus ,

Firstly, thank you for your very instructive share.

I propose you to use string.ContainsAny instead of strings.IndexAny as a new solution for the exercice 04-vowel-or-cons of the chapter 11-if.

**Comment by inancgumus** [comment]
Thanks! As these examples are used within the course videos, can you share a PR that contains this suggestion as a _comment_ on top of the `strings.IndexAny` usage?

**Comment by rkh-hash** [comment]
@inancgumus done :).

**Comment by inancgumus** [comment]
Thanks!!
