### ISSUE TITLE
Lectures deleted on Udemy. Please restore.

### ISSUE THREAD

**Issue by caycaycarly** [inancgumus/learngo#87]
I noticed that a couple dozen lectures have been deleted from the udemy page. The total duration of the course has come down from around 23 hours to 16 hours. That is 7 hours of content. I am guessing that this was just a lapse on your part accomodating the changes in udemy - requiring authors to reupload drm protected content or something. Please restore the deleted lectures asap. Also, you could consider uploading the course as a drm-free attachment in udemy as many other authors are doing right now.

**Comment by inancgumus** [comment]
The total length doesn’t matter as long as you get the same information.
